// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dbx

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/simance-ai/smdx/rpcx/chains/sol/internal/dao/model"
)

func newMarketKline5m(db *gorm.DB, opts ...gen.DOOption) marketKline5m {
	_marketKline5m := marketKline5m{}

	_marketKline5m.marketKline5mDo.UseDB(db, opts...)
	_marketKline5m.marketKline5mDo.UseModel(&model.MarketKline5m{})

	tableName := _marketKline5m.marketKline5mDo.TableName()
	_marketKline5m.ALL = field.NewAsterisk(tableName)
	_marketKline5m.MarketAddress = field.NewString(tableName, "market_address")
	_marketKline5m.O = field.NewFloat64(tableName, "o")
	_marketKline5m.H = field.NewFloat64(tableName, "h")
	_marketKline5m.L = field.NewFloat64(tableName, "l")
	_marketKline5m.C = field.NewFloat64(tableName, "c")
	_marketKline5m.V = field.NewFloat64(tableName, "v")
	_marketKline5m.Timestamp = field.NewTime(tableName, "timestamp")
	_marketKline5m.UpdatedAt = field.NewTime(tableName, "updated_at")
	_marketKline5m.CreatedAt = field.NewTime(tableName, "created_at")

	_marketKline5m.fillFieldMap()

	return _marketKline5m
}

type marketKline5m struct {
	marketKline5mDo marketKline5mDo

	ALL           field.Asterisk
	MarketAddress field.String
	O             field.Float64
	H             field.Float64
	L             field.Float64
	C             field.Float64
	V             field.Float64
	Timestamp     field.Time
	UpdatedAt     field.Time
	CreatedAt     field.Time

	fieldMap map[string]field.Expr
}

func (m marketKline5m) Table(newTableName string) *marketKline5m {
	m.marketKline5mDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m marketKline5m) As(alias string) *marketKline5m {
	m.marketKline5mDo.DO = *(m.marketKline5mDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *marketKline5m) updateTableName(table string) *marketKline5m {
	m.ALL = field.NewAsterisk(table)
	m.MarketAddress = field.NewString(table, "market_address")
	m.O = field.NewFloat64(table, "o")
	m.H = field.NewFloat64(table, "h")
	m.L = field.NewFloat64(table, "l")
	m.C = field.NewFloat64(table, "c")
	m.V = field.NewFloat64(table, "v")
	m.Timestamp = field.NewTime(table, "timestamp")
	m.UpdatedAt = field.NewTime(table, "updated_at")
	m.CreatedAt = field.NewTime(table, "created_at")

	m.fillFieldMap()

	return m
}

func (m *marketKline5m) WithContext(ctx context.Context) *marketKline5mDo {
	return m.marketKline5mDo.WithContext(ctx)
}

func (m marketKline5m) TableName() string { return m.marketKline5mDo.TableName() }

func (m marketKline5m) Alias() string { return m.marketKline5mDo.Alias() }

func (m marketKline5m) Columns(cols ...field.Expr) gen.Columns {
	return m.marketKline5mDo.Columns(cols...)
}

func (m *marketKline5m) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *marketKline5m) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 9)
	m.fieldMap["market_address"] = m.MarketAddress
	m.fieldMap["o"] = m.O
	m.fieldMap["h"] = m.H
	m.fieldMap["l"] = m.L
	m.fieldMap["c"] = m.C
	m.fieldMap["v"] = m.V
	m.fieldMap["timestamp"] = m.Timestamp
	m.fieldMap["updated_at"] = m.UpdatedAt
	m.fieldMap["created_at"] = m.CreatedAt
}

func (m marketKline5m) clone(db *gorm.DB) marketKline5m {
	m.marketKline5mDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m marketKline5m) replaceDB(db *gorm.DB) marketKline5m {
	m.marketKline5mDo.ReplaceDB(db)
	return m
}

type marketKline5mDo struct{ gen.DO }

func (m marketKline5mDo) Debug() *marketKline5mDo {
	return m.withDO(m.DO.Debug())
}

func (m marketKline5mDo) WithContext(ctx context.Context) *marketKline5mDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m marketKline5mDo) ReadDB() *marketKline5mDo {
	return m.Clauses(dbresolver.Read)
}

func (m marketKline5mDo) WriteDB() *marketKline5mDo {
	return m.Clauses(dbresolver.Write)
}

func (m marketKline5mDo) Session(config *gorm.Session) *marketKline5mDo {
	return m.withDO(m.DO.Session(config))
}

func (m marketKline5mDo) Clauses(conds ...clause.Expression) *marketKline5mDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m marketKline5mDo) Returning(value interface{}, columns ...string) *marketKline5mDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m marketKline5mDo) Not(conds ...gen.Condition) *marketKline5mDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m marketKline5mDo) Or(conds ...gen.Condition) *marketKline5mDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m marketKline5mDo) Select(conds ...field.Expr) *marketKline5mDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m marketKline5mDo) Where(conds ...gen.Condition) *marketKline5mDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m marketKline5mDo) Order(conds ...field.Expr) *marketKline5mDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m marketKline5mDo) Distinct(cols ...field.Expr) *marketKline5mDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m marketKline5mDo) Omit(cols ...field.Expr) *marketKline5mDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m marketKline5mDo) Join(table schema.Tabler, on ...field.Expr) *marketKline5mDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m marketKline5mDo) LeftJoin(table schema.Tabler, on ...field.Expr) *marketKline5mDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m marketKline5mDo) RightJoin(table schema.Tabler, on ...field.Expr) *marketKline5mDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m marketKline5mDo) Group(cols ...field.Expr) *marketKline5mDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m marketKline5mDo) Having(conds ...gen.Condition) *marketKline5mDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m marketKline5mDo) Limit(limit int) *marketKline5mDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m marketKline5mDo) Offset(offset int) *marketKline5mDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m marketKline5mDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *marketKline5mDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m marketKline5mDo) Unscoped() *marketKline5mDo {
	return m.withDO(m.DO.Unscoped())
}

func (m marketKline5mDo) Create(values ...*model.MarketKline5m) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m marketKline5mDo) CreateInBatches(values []*model.MarketKline5m, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m marketKline5mDo) Save(values ...*model.MarketKline5m) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m marketKline5mDo) First() (*model.MarketKline5m, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MarketKline5m), nil
	}
}

func (m marketKline5mDo) Take() (*model.MarketKline5m, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MarketKline5m), nil
	}
}

func (m marketKline5mDo) Last() (*model.MarketKline5m, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MarketKline5m), nil
	}
}

func (m marketKline5mDo) Find() ([]*model.MarketKline5m, error) {
	result, err := m.DO.Find()
	return result.([]*model.MarketKline5m), err
}

func (m marketKline5mDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MarketKline5m, err error) {
	buf := make([]*model.MarketKline5m, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m marketKline5mDo) FindInBatches(result *[]*model.MarketKline5m, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m marketKline5mDo) Attrs(attrs ...field.AssignExpr) *marketKline5mDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m marketKline5mDo) Assign(attrs ...field.AssignExpr) *marketKline5mDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m marketKline5mDo) Joins(fields ...field.RelationField) *marketKline5mDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m marketKline5mDo) Preload(fields ...field.RelationField) *marketKline5mDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m marketKline5mDo) FirstOrInit() (*model.MarketKline5m, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MarketKline5m), nil
	}
}

func (m marketKline5mDo) FirstOrCreate() (*model.MarketKline5m, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MarketKline5m), nil
	}
}

func (m marketKline5mDo) FindByPage(offset int, limit int) (result []*model.MarketKline5m, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m marketKline5mDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m marketKline5mDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m marketKline5mDo) Delete(models ...*model.MarketKline5m) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *marketKline5mDo) withDO(do gen.Dao) *marketKline5mDo {
	m.DO = *do.(*gen.DO)
	return m
}
