// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dbx

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/simance-ai/smdx/rpcx/chains/sol/internal/dao/model"
)

func newMarketKline1h(db *gorm.DB, opts ...gen.DOOption) marketKline1h {
	_marketKline1h := marketKline1h{}

	_marketKline1h.marketKline1hDo.UseDB(db, opts...)
	_marketKline1h.marketKline1hDo.UseModel(&model.MarketKline1h{})

	tableName := _marketKline1h.marketKline1hDo.TableName()
	_marketKline1h.ALL = field.NewAsterisk(tableName)
	_marketKline1h.MarketAddress = field.NewString(tableName, "market_address")
	_marketKline1h.O = field.NewFloat64(tableName, "o")
	_marketKline1h.H = field.NewFloat64(tableName, "h")
	_marketKline1h.L = field.NewFloat64(tableName, "l")
	_marketKline1h.C = field.NewFloat64(tableName, "c")
	_marketKline1h.V = field.NewFloat64(tableName, "v")
	_marketKline1h.Timestamp = field.NewTime(tableName, "timestamp")
	_marketKline1h.UpdatedAt = field.NewTime(tableName, "updated_at")
	_marketKline1h.CreatedAt = field.NewTime(tableName, "created_at")

	_marketKline1h.fillFieldMap()

	return _marketKline1h
}

type marketKline1h struct {
	marketKline1hDo marketKline1hDo

	ALL           field.Asterisk
	MarketAddress field.String
	O             field.Float64
	H             field.Float64
	L             field.Float64
	C             field.Float64
	V             field.Float64
	Timestamp     field.Time
	UpdatedAt     field.Time
	CreatedAt     field.Time

	fieldMap map[string]field.Expr
}

func (m marketKline1h) Table(newTableName string) *marketKline1h {
	m.marketKline1hDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m marketKline1h) As(alias string) *marketKline1h {
	m.marketKline1hDo.DO = *(m.marketKline1hDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *marketKline1h) updateTableName(table string) *marketKline1h {
	m.ALL = field.NewAsterisk(table)
	m.MarketAddress = field.NewString(table, "market_address")
	m.O = field.NewFloat64(table, "o")
	m.H = field.NewFloat64(table, "h")
	m.L = field.NewFloat64(table, "l")
	m.C = field.NewFloat64(table, "c")
	m.V = field.NewFloat64(table, "v")
	m.Timestamp = field.NewTime(table, "timestamp")
	m.UpdatedAt = field.NewTime(table, "updated_at")
	m.CreatedAt = field.NewTime(table, "created_at")

	m.fillFieldMap()

	return m
}

func (m *marketKline1h) WithContext(ctx context.Context) *marketKline1hDo {
	return m.marketKline1hDo.WithContext(ctx)
}

func (m marketKline1h) TableName() string { return m.marketKline1hDo.TableName() }

func (m marketKline1h) Alias() string { return m.marketKline1hDo.Alias() }

func (m marketKline1h) Columns(cols ...field.Expr) gen.Columns {
	return m.marketKline1hDo.Columns(cols...)
}

func (m *marketKline1h) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *marketKline1h) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 9)
	m.fieldMap["market_address"] = m.MarketAddress
	m.fieldMap["o"] = m.O
	m.fieldMap["h"] = m.H
	m.fieldMap["l"] = m.L
	m.fieldMap["c"] = m.C
	m.fieldMap["v"] = m.V
	m.fieldMap["timestamp"] = m.Timestamp
	m.fieldMap["updated_at"] = m.UpdatedAt
	m.fieldMap["created_at"] = m.CreatedAt
}

func (m marketKline1h) clone(db *gorm.DB) marketKline1h {
	m.marketKline1hDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m marketKline1h) replaceDB(db *gorm.DB) marketKline1h {
	m.marketKline1hDo.ReplaceDB(db)
	return m
}

type marketKline1hDo struct{ gen.DO }

func (m marketKline1hDo) Debug() *marketKline1hDo {
	return m.withDO(m.DO.Debug())
}

func (m marketKline1hDo) WithContext(ctx context.Context) *marketKline1hDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m marketKline1hDo) ReadDB() *marketKline1hDo {
	return m.Clauses(dbresolver.Read)
}

func (m marketKline1hDo) WriteDB() *marketKline1hDo {
	return m.Clauses(dbresolver.Write)
}

func (m marketKline1hDo) Session(config *gorm.Session) *marketKline1hDo {
	return m.withDO(m.DO.Session(config))
}

func (m marketKline1hDo) Clauses(conds ...clause.Expression) *marketKline1hDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m marketKline1hDo) Returning(value interface{}, columns ...string) *marketKline1hDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m marketKline1hDo) Not(conds ...gen.Condition) *marketKline1hDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m marketKline1hDo) Or(conds ...gen.Condition) *marketKline1hDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m marketKline1hDo) Select(conds ...field.Expr) *marketKline1hDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m marketKline1hDo) Where(conds ...gen.Condition) *marketKline1hDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m marketKline1hDo) Order(conds ...field.Expr) *marketKline1hDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m marketKline1hDo) Distinct(cols ...field.Expr) *marketKline1hDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m marketKline1hDo) Omit(cols ...field.Expr) *marketKline1hDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m marketKline1hDo) Join(table schema.Tabler, on ...field.Expr) *marketKline1hDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m marketKline1hDo) LeftJoin(table schema.Tabler, on ...field.Expr) *marketKline1hDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m marketKline1hDo) RightJoin(table schema.Tabler, on ...field.Expr) *marketKline1hDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m marketKline1hDo) Group(cols ...field.Expr) *marketKline1hDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m marketKline1hDo) Having(conds ...gen.Condition) *marketKline1hDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m marketKline1hDo) Limit(limit int) *marketKline1hDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m marketKline1hDo) Offset(offset int) *marketKline1hDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m marketKline1hDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *marketKline1hDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m marketKline1hDo) Unscoped() *marketKline1hDo {
	return m.withDO(m.DO.Unscoped())
}

func (m marketKline1hDo) Create(values ...*model.MarketKline1h) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m marketKline1hDo) CreateInBatches(values []*model.MarketKline1h, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m marketKline1hDo) Save(values ...*model.MarketKline1h) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m marketKline1hDo) First() (*model.MarketKline1h, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MarketKline1h), nil
	}
}

func (m marketKline1hDo) Take() (*model.MarketKline1h, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MarketKline1h), nil
	}
}

func (m marketKline1hDo) Last() (*model.MarketKline1h, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MarketKline1h), nil
	}
}

func (m marketKline1hDo) Find() ([]*model.MarketKline1h, error) {
	result, err := m.DO.Find()
	return result.([]*model.MarketKline1h), err
}

func (m marketKline1hDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MarketKline1h, err error) {
	buf := make([]*model.MarketKline1h, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m marketKline1hDo) FindInBatches(result *[]*model.MarketKline1h, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m marketKline1hDo) Attrs(attrs ...field.AssignExpr) *marketKline1hDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m marketKline1hDo) Assign(attrs ...field.AssignExpr) *marketKline1hDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m marketKline1hDo) Joins(fields ...field.RelationField) *marketKline1hDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m marketKline1hDo) Preload(fields ...field.RelationField) *marketKline1hDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m marketKline1hDo) FirstOrInit() (*model.MarketKline1h, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MarketKline1h), nil
	}
}

func (m marketKline1hDo) FirstOrCreate() (*model.MarketKline1h, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MarketKline1h), nil
	}
}

func (m marketKline1hDo) FindByPage(offset int, limit int) (result []*model.MarketKline1h, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m marketKline1hDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m marketKline1hDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m marketKline1hDo) Delete(models ...*model.MarketKline1h) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *marketKline1hDo) withDO(do gen.Dao) *marketKline1hDo {
	m.DO = *do.(*gen.DO)
	return m
}
