// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMarketTx = "market_tx"

// MarketTx mapped from table <market_tx>
type MarketTx struct {
	MarketAddress    string    `gorm:"column:market_address" json:"market_address"`
	QuoteAmount      float64   `gorm:"column:quote_amount" json:"quote_amount"`
	Volume           float64   `gorm:"column:volume" json:"volume"`
	QuotePrice       float64   `gorm:"column:quote_price" json:"quote_price"`
	TxType           int32     `gorm:"column:tx_type" json:"tx_type"`
	BasePrice        float64   `gorm:"column:base_price" json:"base_price"`
	TxHash           string    `gorm:"column:tx_hash" json:"tx_hash"`
	Slot             int32     `gorm:"column:slot" json:"slot"`
	QuoteAddress     string    `gorm:"column:quote_address" json:"quote_address"`
	MakerAddress     string    `gorm:"column:maker_address" json:"maker_address"`
	BaseAmount       float64   `gorm:"column:base_amount" json:"base_amount"`
	CreatedTimestamp time.Time `gorm:"column:created_timestamp" json:"created_timestamp"`
	CreatedAt        time.Time `gorm:"column:created_at;default:now()" json:"created_at"`
}

// TableName MarketTx's table name
func (*MarketTx) TableName() string {
	return TableNameMarketTx
}
