// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMarketAuditMedium = "market_audit_media"

// MarketAuditMedium mapped from table <market_audit_media>
type MarketAuditMedium struct {
	Address                string  `gorm:"column:address" json:"address"`
	Name                   string  `gorm:"column:name" json:"name"`
	Description            string  `gorm:"column:description" json:"description"`
	RenouncedFreezeAccount bool    `gorm:"column:renounced_freeze_account" json:"renounced_freeze_account"`
	RenouncedMint          bool    `gorm:"column:renounced_mint" json:"renounced_mint"`
	CreatorClose           bool    `gorm:"column:creator_close" json:"creator_close"`
	Top10HolderRate        float64 `gorm:"column:top10_holder_rate" json:"top10_holder_rate"`
	LpBurntRate            float64 `gorm:"column:lp_burnt_rate" json:"lp_burnt_rate"`
	CreatorTokenStatus     bool    `gorm:"column:creator_token_status" json:"creator_token_status"`
	OfficialWebsite        string  `gorm:"column:official_website" json:"official_website"`
	Telegram               string  `gorm:"column:telegram" json:"telegram"`
	Twitter                string  `gorm:"column:twitter" json:"twitter"`
	Facebook               string  `gorm:"column:facebook" json:"facebook"`
	Reddit                 string  `gorm:"column:reddit" json:"reddit"`
	Github                 string  `gorm:"column:github" json:"github"`
	Whitepaper             string  `gorm:"column:whitepaper" json:"whitepaper"`
	HotLevel               int32   `gorm:"column:hot_level" json:"hot_level"`
	QuoteMaxSupply         float64 `gorm:"column:quote_max_supply" json:"quote_max_supply"`
}

// TableName MarketAuditMedium's table name
func (*MarketAuditMedium) TableName() string {
	return TableNameMarketAuditMedium
}
