// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMarketRealTimeDatum = "market_real_time_data"

// MarketRealTimeDatum mapped from table <market_real_time_data>
type MarketRealTimeDatum struct {
	Address        string    `gorm:"column:address" json:"address"`
	QuotePrice     float64   `gorm:"column:quote_price" json:"quote_price"`
	BasePrice      float64   `gorm:"column:base_price" json:"base_price"`
	QuoteVault     float64   `gorm:"column:quote_vault;comment:引用币数量" json:"quote_vault"` // 引用币数量
	BaseVault      float64   `gorm:"column:base_vault;comment:基础币数量" json:"base_vault"`   // 基础币数量
	Liquidity      float64   `gorm:"column:liquidity;comment:流动性大小usd" json:"liquidity"`  // 流动性大小usd
	MarketCap      float64   `gorm:"column:market_cap;comment:市值 usd" json:"market_cap"`  // 市值 usd
	HolderCount    int64     `gorm:"column:holder_count" json:"holder_count"`
	Swaps          int64     `gorm:"column:swaps" json:"swaps"`
	Sells          int64     `gorm:"column:sells" json:"sells"`
	Buys           int64     `gorm:"column:buys" json:"buys"`
	Volume         float64   `gorm:"column:volume" json:"volume"`
	PriceChange1m  float64   `gorm:"column:price_change_1m" json:"price_change_1m"`
	PriceChange5m  float64   `gorm:"column:price_change_5m" json:"price_change_5m"`
	PriceChange1h  float64   `gorm:"column:price_change_1h" json:"price_change_1h"`
	PriceChange6h  float64   `gorm:"column:price_change_6h" json:"price_change_6h"`
	PriceChange24h float64   `gorm:"column:price_change_24h" json:"price_change_24h"`
	SellVolume1m   float64   `gorm:"column:sell_volume_1m" json:"sell_volume_1m"`
	SellVolume5m   float64   `gorm:"column:sell_volume_5m" json:"sell_volume_5m"`
	SellVolume1h   float64   `gorm:"column:sell_volume_1h" json:"sell_volume_1h"`
	SellVolume6h   float64   `gorm:"column:sell_volume_6h" json:"sell_volume_6h"`
	SellVolume24h  float64   `gorm:"column:sell_volume_24h" json:"sell_volume_24h"`
	BuyVolume1m    float64   `gorm:"column:buy_volume_1m" json:"buy_volume_1m"`
	BuyVolume5m    float64   `gorm:"column:buy_volume_5m" json:"buy_volume_5m"`
	BuyVolume1h    float64   `gorm:"column:buy_volume_1h" json:"buy_volume_1h"`
	BuyVolume6h    float64   `gorm:"column:buy_volume_6h" json:"buy_volume_6h"`
	BuyVolume24h   float64   `gorm:"column:buy_volume_24h" json:"buy_volume_24h"`
	BuyCount1m     float64   `gorm:"column:buy_count_1m" json:"buy_count_1m"`
	BuyCount5m     float64   `gorm:"column:buy_count_5m" json:"buy_count_5m"`
	BuyCount1h     float64   `gorm:"column:buy_count_1h" json:"buy_count_1h"`
	BuyCount6h     float64   `gorm:"column:buy_count_6h" json:"buy_count_6h"`
	BuyCount24h    float64   `gorm:"column:buy_count_24h" json:"buy_count_24h"`
	SellCount1m    float64   `gorm:"column:sell_count_1m" json:"sell_count_1m"`
	SellCount5m    float64   `gorm:"column:sell_count_5m" json:"sell_count_5m"`
	SellCount1h    float64   `gorm:"column:sell_count_1h" json:"sell_count_1h"`
	SellCount6h    float64   `gorm:"column:sell_count_6h" json:"sell_count_6h"`
	SellCount24h   float64   `gorm:"column:sell_count_24h" json:"sell_count_24h"`
	Age            time.Time `gorm:"column:age" json:"age"`
	PriceChange30m float64   `gorm:"column:price_change_30m" json:"price_change_30m"`
	SellVolume30m  float64   `gorm:"column:sell_volume_30m" json:"sell_volume_30m"`
	BuyVolume30m   float64   `gorm:"column:buy_volume_30m" json:"buy_volume_30m"`
	BuyCount30m    float64   `gorm:"column:buy_count_30m" json:"buy_count_30m"`
	SellCount30m   float64   `gorm:"column:sell_count_30m" json:"sell_count_30m"`
	DevBaseBalance float64   `gorm:"column:dev_base_balance" json:"dev_base_balance"`
	Fdv            float64   `gorm:"column:fdv;comment:流通市值" json:"fdv"` // 流通市值
}

// TableName MarketRealTimeDatum's table name
func (*MarketRealTimeDatum) TableName() string {
	return TableNameMarketRealTimeDatum
}
