// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.11
// source: rebate.proto

package rebate

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Rebate_Ping_FullMethodName = "/rebate.Rebate/Ping"
)

// RebateClient is the client API for Rebate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RebateClient interface {
	Ping(ctx context.Context, in *RebateRequest, opts ...grpc.CallOption) (*RebateResponse, error)
}

type rebateClient struct {
	cc grpc.ClientConnInterface
}

func NewRebateClient(cc grpc.ClientConnInterface) RebateClient {
	return &rebateClient{cc}
}

func (c *rebateClient) Ping(ctx context.Context, in *RebateRequest, opts ...grpc.CallOption) (*RebateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RebateResponse)
	err := c.cc.Invoke(ctx, Rebate_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RebateServer is the server API for Rebate service.
// All implementations must embed UnimplementedRebateServer
// for forward compatibility.
type RebateServer interface {
	Ping(context.Context, *RebateRequest) (*RebateResponse, error)
	mustEmbedUnimplementedRebateServer()
}

// UnimplementedRebateServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRebateServer struct{}

func (UnimplementedRebateServer) Ping(context.Context, *RebateRequest) (*RebateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedRebateServer) mustEmbedUnimplementedRebateServer() {}
func (UnimplementedRebateServer) testEmbeddedByValue()                {}

// UnsafeRebateServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RebateServer will
// result in compilation errors.
type UnsafeRebateServer interface {
	mustEmbedUnimplementedRebateServer()
}

func RegisterRebateServer(s grpc.ServiceRegistrar, srv RebateServer) {
	// If the following call pancis, it indicates UnimplementedRebateServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Rebate_ServiceDesc, srv)
}

func _Rebate_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RebateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RebateServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rebate_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RebateServer).Ping(ctx, req.(*RebateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Rebate_ServiceDesc is the grpc.ServiceDesc for Rebate service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Rebate_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rebate.Rebate",
	HandlerType: (*RebateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Rebate_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rebate.proto",
}
