// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.20.3
// source: ws.proto

package ws

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Ws_FireMarketKline_FullMethodName      = "/ws.Ws/FireMarketKline"
	Ws_FireMarketTxActivity_FullMethodName = "/ws.Ws/FireMarketTxActivity"
)

// WsClient is the client API for Ws service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WsClient interface {
	// FireMarketKline
	FireMarketKline(ctx context.Context, in *FireMarketKlineRequest, opts ...grpc.CallOption) (*FireMarketKlineResponse, error)
	FireMarketTxActivity(ctx context.Context, in *FireMarketTxActivityRequest, opts ...grpc.CallOption) (*FireMarketTxActivityResponse, error)
}

type wsClient struct {
	cc grpc.ClientConnInterface
}

func NewWsClient(cc grpc.ClientConnInterface) WsClient {
	return &wsClient{cc}
}

func (c *wsClient) FireMarketKline(ctx context.Context, in *FireMarketKlineRequest, opts ...grpc.CallOption) (*FireMarketKlineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FireMarketKlineResponse)
	err := c.cc.Invoke(ctx, Ws_FireMarketKline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wsClient) FireMarketTxActivity(ctx context.Context, in *FireMarketTxActivityRequest, opts ...grpc.CallOption) (*FireMarketTxActivityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FireMarketTxActivityResponse)
	err := c.cc.Invoke(ctx, Ws_FireMarketTxActivity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WsServer is the server API for Ws service.
// All implementations must embed UnimplementedWsServer
// for forward compatibility.
type WsServer interface {
	// FireMarketKline
	FireMarketKline(context.Context, *FireMarketKlineRequest) (*FireMarketKlineResponse, error)
	FireMarketTxActivity(context.Context, *FireMarketTxActivityRequest) (*FireMarketTxActivityResponse, error)
	mustEmbedUnimplementedWsServer()
}

// UnimplementedWsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWsServer struct{}

func (UnimplementedWsServer) FireMarketKline(context.Context, *FireMarketKlineRequest) (*FireMarketKlineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FireMarketKline not implemented")
}
func (UnimplementedWsServer) FireMarketTxActivity(context.Context, *FireMarketTxActivityRequest) (*FireMarketTxActivityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FireMarketTxActivity not implemented")
}
func (UnimplementedWsServer) mustEmbedUnimplementedWsServer() {}
func (UnimplementedWsServer) testEmbeddedByValue()            {}

// UnsafeWsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WsServer will
// result in compilation errors.
type UnsafeWsServer interface {
	mustEmbedUnimplementedWsServer()
}

func RegisterWsServer(s grpc.ServiceRegistrar, srv WsServer) {
	// If the following call pancis, it indicates UnimplementedWsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Ws_ServiceDesc, srv)
}

func _Ws_FireMarketKline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FireMarketKlineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WsServer).FireMarketKline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ws_FireMarketKline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WsServer).FireMarketKline(ctx, req.(*FireMarketKlineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ws_FireMarketTxActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FireMarketTxActivityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WsServer).FireMarketTxActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ws_FireMarketTxActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WsServer).FireMarketTxActivity(ctx, req.(*FireMarketTxActivityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Ws_ServiceDesc is the grpc.ServiceDesc for Ws service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ws_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ws.Ws",
	HandlerType: (*WsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FireMarketKline",
			Handler:    _Ws_FireMarketKline_Handler,
		},
		{
			MethodName: "FireMarketTxActivity",
			Handler:    _Ws_FireMarketTxActivity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ws.proto",
}
