// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.5

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	rebateDetailFieldNames          = builder.RawFieldNames(&RebateDetail{}, true)
	rebateDetailRows                = strings.Join(rebateDetailFieldNames, ",")
	rebateDetailRowsExpectAutoSet   = strings.Join(stringx.Remove(rebateDetailFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	rebateDetailRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(rebateDetailFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))

	cachePublicRebateDetailIdPrefix = "cache:public:rebateDetail:id:"
)

type (
	rebateDetailModel interface {
		Insert(ctx context.Context, data *RebateDetail) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*RebateDetail, error)
		Update(ctx context.Context, data *RebateDetail) error
		Delete(ctx context.Context, id int64) error
	}

	defaultRebateDetailModel struct {
		sqlc.CachedConn
		table string
	}

	RebateDetail struct {
		Id           int64     `db:"id"`
		Address      string    `db:"address"`
		CreatedAt    time.Time `db:"created_at"`
		RebateAmount float64     `db:"rebate_amount"`
	}
)

func newRebateDetailModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultRebateDetailModel {
	return &defaultRebateDetailModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      `"public"."rebate_detail"`,
	}
}

func (m *defaultRebateDetailModel) Delete(ctx context.Context, id int64) error {
	publicRebateDetailIdKey := fmt.Sprintf("%s%v", cachePublicRebateDetailIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where id = $1", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, publicRebateDetailIdKey)
	return err
}

func (m *defaultRebateDetailModel) FindOne(ctx context.Context, id int64) (*RebateDetail, error) {
	publicRebateDetailIdKey := fmt.Sprintf("%s%v", cachePublicRebateDetailIdPrefix, id)
	var resp RebateDetail
	err := m.QueryRowCtx(ctx, &resp, publicRebateDetailIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where id = $1 limit 1", rebateDetailRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRebateDetailModel) Insert(ctx context.Context, data *RebateDetail) (sql.Result, error) {
	publicRebateDetailIdKey := fmt.Sprintf("%s%v", cachePublicRebateDetailIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values ($1, $2)", m.table, rebateDetailRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Address, data.RebateAmount)
	}, publicRebateDetailIdKey)
	return ret, err
}

func (m *defaultRebateDetailModel) Update(ctx context.Context, data *RebateDetail) error {
	publicRebateDetailIdKey := fmt.Sprintf("%s%v", cachePublicRebateDetailIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where id = $1", m.table, rebateDetailRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Id, data.Address, data.RebateAmount)
	}, publicRebateDetailIdKey)
	return err
}

func (m *defaultRebateDetailModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cachePublicRebateDetailIdPrefix, primary)
}

func (m *defaultRebateDetailModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", rebateDetailRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultRebateDetailModel) tableName() string {
	return m.table
}

