// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.5
// Source: eth.proto

package server

import (
	"context"

	"github.com/simance-ai/smdx/rpcx/chains/eth/eth"
	"github.com/simance-ai/smdx/rpcx/chains/eth/internal/logic"
	"github.com/simance-ai/smdx/rpcx/chains/eth/internal/svc"
)

type EthServer struct {
	svcCtx *svc.ServiceContext
	eth.UnimplementedEthServer
}

func NewEthServer(svcCtx *svc.ServiceContext) *EthServer {
	return &EthServer{
		svcCtx: svcCtx,
	}
}

func (s *EthServer) Ping(ctx context.Context, in *eth.Request) (*eth.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
