// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.5
// Source: order.proto

package server

import (
	"context"

	"github.com/simance-ai/smdx/rpcx/order/internal/logic"
	"github.com/simance-ai/smdx/rpcx/order/internal/svc"
	"github.com/simance-ai/smdx/rpcx/order/order"
)

type OrderServer struct {
	svcCtx *svc.ServiceContext
	order.UnimplementedOrderServer
}

func NewOrderServer(svcCtx *svc.ServiceContext) *OrderServer {
	return &OrderServer{
		svcCtx: svcCtx,
	}
}

func (s *OrderServer) Ping(ctx context.Context, in *order.Request) (*order.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

func (s *OrderServer) CreateOrder(ctx context.Context, in *order.CreateOrderRequest) (*order.CreateOrderResponse, error) {
	l := logic.NewCreateOrderLogic(ctx, s.svcCtx)
	return l.CreateOrder(in)
}

func (s *OrderServer) QueryOrder(ctx context.Context, in *order.QueryOrderRequest) (*order.QueryOrderResponse, error) {
	l := logic.NewQueryOrderLogic(ctx, s.svcCtx)
	return l.QueryOrder(in)
}

func (s *OrderServer) GetOrderDetail(ctx context.Context, in *order.GetOrderDetailRequest) (*order.GetOrderDetailResponse, error) {
	l := logic.NewGetOrderDetailLogic(ctx, s.svcCtx)
	return l.GetOrderDetail(in)
}

func (s *OrderServer) GetOrderList(ctx context.Context, in *order.GetOrderListRequest) (*order.OrderListResponse, error) {
	l := logic.NewGetOrderListLogic(ctx, s.svcCtx)
	return l.GetOrderList(in)
}

func (s *OrderServer) GetRebateOrderList(ctx context.Context, in *order.RebateOrderListRequest) (*order.RebateOrderListResponse, error) {
	l := logic.NewGetRebateOrderListLogic(ctx, s.svcCtx)
	return l.GetRebateOrderList(in)
}

func (s *OrderServer) UpdateRebateOrder(ctx context.Context, in *order.UpdateRebateOrderRequest) (*order.Response, error) {
	l := logic.NewUpdateRebateOrderLogic(ctx, s.svcCtx)
	return l.UpdateRebateOrder(in)
}

func (s *OrderServer) GetAccountOrderInfo(ctx context.Context, in *order.GetAccountInfoRequest) (*order.GetAccountInfoResponse, error) {
	l := logic.NewGetAccountOrderInfoLogic(ctx, s.svcCtx)
	return l.GetAccountOrderInfo(in)
}
